" Disable legacy features
set nocompatible
set nobackup
set nowritebackup
set noswapfile
set scrolloff=3
set showtabline=2
set laststatus=2
set showcmd
set showmatch
set autoread
set confirm

" Set colorscheme
colorscheme desert2

" Language
language ru

" File optiions
set fileencoding=utf-8
set fileformat=unix

syntax on

" Set tab options
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab
set softtabstop=2
set autoindent
set backspace=indent,eol,start

" Set some char visble
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set nolist
set shortmess+=I
set viminfo^=h

" Folding options
set foldenable
set foldmethod=indent
set foldcolumn=3
set foldlevel=1
set foldopen=all

if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

" Enable mouse
set mouse=a
set mousehide

" Set key maps
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0

" Setup and turn off spell check
set spell spelllang=ru_yo,en_us
set nospell

" Syntax hiliting reload
noremap <F12> <Esc>:syntax sync fromstart<CR>
inoremap <F12> <C-o>:syntax sync fromstart<CR>

" Text moving
nnoremap <C-j> :m .+1<CR>
nnoremap <C-k> :m .-2<CR>
inoremap <C-j> <Esc>:m .+1<CR>i
inoremap <C-k> <Esc>:m .-2<CR>i
vnoremap <C-j> :m '>+1<CR>gv
vnoremap <C-k> :m '<-2<CR>gv

" Windows resizing
nnoremap <M-Left> <C-W><
nnoremap <M-Up> <C-W>+
nnoremap <M-Right> <C-W>>
nnoremap <M-Down> <C-W>-


" Show syntax
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

" Gui options
if has("gui")
  set guioptions-=T
  if g:os == "Windows"
    set guifont=Consolas:h12:cRUSSIAN
  endif
else
  set termencoding=utf-8
  " KDE Konsole cursor swithing
  let &t_SI = "\<Esc>]50;CursorShape=1;BlinkingCursorEnabled=1\x7"
  let &t_SR = "\<Esc>]50;CursorShape=2;BlinkingCursorEnabled=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0;BlinkingCursorEnabled=0\x7"
endif

"set hilite row and column switch key
":nnoremap H :set cursorline! cursorcolumn!<CR>

" Clear grep parameters for full usage
"set grepprg=grep
"
" Turn on row numbering
set number
set number relativenumber
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
"  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

"=====================================================
" PLUGIN SETTINGS
"=====================================================
" Vundle settings
"=====================================================
filetype off                  " required
" set the runtime path to include Vundle and initialize
if g:os=="Windows"
    set rtp+=$HOME\vimfiles\bundle\Vundle.vim
else
    set rtp+=~/.vim/bundle/Vundle.vim/
endif

call vundle#begin()
Plugin 'gmarik/Vundle.vim'              " let Vundle manage Vundle, required
Plugin 'scrooloose/nerdtree'            " Project and file navigation
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
call vundle#end()                       " required
filetype on
filetype plugin on                      " end of Vundle config

" NerdTree 
map <F3> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$']  

" Lightline options
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ 'active': {
      \   'left':  [ [ 'mode', 'paste' ],
      \              [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'totallines', 'percent' ],
      \              [ 'charinfo', 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component': {
      \   'charinfo': 'ASCII=%03.3b HEX=%02.2B',
      \   'totallines': 'L=%L'
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ }
      \ }
